version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.2
    working_directory: ~/repo/server/app/Todoist
    steps:
      - checkout
      - run: composer install
      - run: composer test
orbs:
  aws-code-deploy: circleci/aws-code-deploy@0.0.9
workflows:
  build_and_deploy_application:
    jobs:
      - build
      - aws-code-deploy/deploy:
          requires:
            - build
          application-name: Todoist_Laravel
          deployment-group: Todoist_Laravel-Group
          service-role-arn: arn:aws:iam::297785152575:role/CodeDeployServiceRole
          bundle-bucket: todoist-laravel
          bundle-key: ${CIRCLE_BRANCH}_${CIRCLE_SHA1}
