version: 2.1
orbs:
  aws-code-deploy: circleci/aws-code-deploy@0.0.9
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: Todoist_Laravel
          deployment-group: Todoist_Laravel-Group
          service-role-arn: arn:aws:iam::297785152575:role/CodeDeployServiceRole
          bundle-bucket: todoist-laravel
          bundle-key: ${CIRCLE_BRANCH}_${CIRCLE_SHA1}
