version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers

    environment:
      APP_KEY: base64:SDxj00KNc1WA+5Lh/xUDNXl/F3wepch+A8zZsBEfl4E=

    working_directory: ~/project/server/app/Todoist

    steps:
      - checkout:
          path: ~/project

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: composer test
orbs:
  aws-code-deploy: circleci/aws-code-deploy@0.0.9
workflows:
  build_and_deploy_application:
    jobs:
      - build
      - aws-code-deploy/deploy:
          branches:
            only:
              - master
          requires:
            - build
          application-name: Todoist_Laravel
          deployment-group: Todoist_Laravel-Group
          service-role-arn: arn:aws:iam::297785152575:role/CodeDeployServiceRole
          bundle-bucket: todoist-laravel
          bundle-key: ${CIRCLE_BRANCH}_${CIRCLE_SHA1}
